import matplotlib.pyplot as plt
import sys
import numpy as np
import csv
import argparse

"""
    Plot a CSV generated by an FftDevice
"""

def plot_csv(filepath):
    raw_data = []
    with open(filepath, 'rb') as csvfile:
        csv_reader = csv.reader(csvfile, delimiter=',', quotechar='|')
        for row in csv_reader:
            raw_data.append([float(x) for x in row])
    raw_data = np.array(raw_data).astype(float)

    t = raw_data[:, 0]
    bands = raw_data[:, 1:]

    for i, band in enumerate(bands.T):
        plt.plot(t, band, label="Band %i"%(i+1))

    plt.xlabel('Time (s)')
    plt.ylabel('Intensity')
    plt.legend()
    plt.show()

def main(args):
    parser = argparse.ArgumentParser("Plot a CSV of fft data")
    parser.add_argument("filepath", help="filepath to csv")

    parser_args = parser.parse_args(args)
    plot_csv(parser_args.filepath)


if __name__=='__main__':
    main(sys.argv[1:])